name: Run Jupyter Notebook on Push

on:
  push:
    branches:
      - main  # or any branch you want to monitor

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # or the Python version your notebook requires

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a `requirements.txt` file listing necessary packages
        pip install jupyter nbconvert  # Required to run notebooks
        pip install papermill  # Alternatively, to execute and parametrize the notebook

    # Step 4: Set environment variables for MLflow (DagsHub)
    - name: Set DagsHub MLflow credentials
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}  # Add this as a secret in GitHub
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}  # Add this as a secret in GitHub

    # Step 5: Run the notebook
    - name: Run notebook
      run: |
        jupyter nbconvert --execute --to notebook --inplace /path/to/your/notebook.ipynb
        # OR use papermill to run the notebook:
        # papermill /path/to/your/notebook.ipynb /path/to/your/output.ipynb

    # Optional: Save the modified notebook as an artifact
    #- name: Upload Notebook
     # uses: actions/upload-artifact@v3
      #with:
       # name: executed-notebook
       # path: /path/to/your/notebook.ipynb
