name: Run Jupyter Notebook on Push

on:
  push:
    branches:
      - main  # Ensure this matches your repository's branch (or use 'master' if that's your default branch)

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure requirements.txt is in the repository root

    # Debug: Check installed packages
    - name: List installed packages
      run: pip freeze

    # Step 4: Set environment variables for MLflow (DagsHub)
    - name: Set DagsHub MLflow credentials
      run: echo "Setting MLflow credentials"  # Using a run command here just to output some text for clarity
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}  # Ensure these secrets are set in your GitHub repository
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}  # Ensure these secrets are set in your GitHub repository

    # Step 5: Run the notebook
    - name: Run notebook
      run: |
        jupyter nbconvert --execute --to notebook --inplace modeling-wind-power-forecasting.ipynb || cat modeling-wind-power-forecasting.ipynb
