name: mlops-example-tensorflow-regression

permissions:
  id-token: write
  contents: write

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install dependencies
          pip install -r requirements.txt
          
          # Run Jupyter notebook
          jupyter nbconvert --to notebook --execute --inplace --ExecutePreprocessor.timeout=600 modeling-wind-power-forecasting.ipynb
          
          # Collect model metrics
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          # Post metrics as a comment to the GitHub PR or commit
          cml comment create report.md
