name: Deploy to the Hugging Faces Hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          lfs: true

      # Remove large files to prevent push errors
      - name: Install dependenciess
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install dvc[s3] 

       # Set up DVC (for DagsHub storage)
      - name: Set up DVC
        run: |
          # Configure DVC remote to use DagsHub as storage
          dvc remote add origin s3://dvc
          dvc remote modify origin endpointurl https://dagshub.com/allmamun556/MLOPS_CI_CD_MONITORING.s3
          dvc remote modify origin --local access_key_id ${{ secrets.DVC_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DVC_SECRET_ACCESS_KEY }}

      # Pull data from DVC remote (DagsHub)
      - name: Pull data from DVC remote
        run: |
          dvc pull -r origin  # Pull data from the configured remote (DagsHub)         

      - name: Run unit tests
        run: |
          python -m unittest discover tests  # Runs all tests in the "test" directory    

      - name: Remove large files
        run: |
          git rm --cached Turbine_Data.csv || true
          echo "Turbine_Data.csv" >> .gitignore
          git add .gitignore
          git commit -m "Exclude large files from push" || true

      - name: Push to Hugging Face Hub

        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://mamunds:$HF_TOKEN@huggingface.co/spaces/mamunds/mlops main
