name: Sync to Hugging Face hub
on:
  push:
    branches: [master]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Add Turbine_Data.csv to .gitignore
        run: |
          echo "Turbine_Data.csv" >> .gitignore
          git rm --cached Turbine_Data.csv || echo "Turbine_Data.csv was not tracked"
          git add .gitignore
          git commit -m "Ignore Turbine_Data.csv" || echo "No changes to commit"

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://mamunds:$HF_TOKEN@huggingface.co/spaces/mamunds/mlops master
