name: Sync to Hugging Face hub
on:
  push:
    branches: [master]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # Ensure Git LFS is initialized (necessary if working with large files)
      - name: Initialize Git LFS
        run: |
          git lfs install
          git lfs track "Turbine_Data.csv"
          git add .gitattributes
          git commit -m "Track large files with Git LFS" || echo "No changes to commit"

      # Exclude Turbine_Data.csv from the commit
      - name: Remove Turbine_Data.csv from history if it exists
        run: |
          if [ -f "Turbine_Data.csv" ]; then
            git rm --cached Turbine_Data.csv
            git commit -m "Exclude Turbine_Data.csv from push" || echo "No changes to commit"
          else
            echo "Turbine_Data.csv does not exist in the repo."
          fi

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://mamunds:$HF_TOKEN@huggingface.co/spaces/mamunds/mlops master
