name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc[s3]  # Install DVC with the required remote (e.g., s3 or dagshub)

    # Set up DVC (for DagsHub storage)
    - name: Set up DVC
      run: |
        # Configure DVC remote to use DagsHub as storage
        dvc remote add origin s3://dvc
        dvc remote modify origin endpointurl https://dagshub.com/allmamun556/MLOPS_CI_CD_MONITORING.s3
        dvc remote modify origin --local access_key_id e93226059eb069c73f4c2738187b0a881fb403fa
        dvc remote modify origin --local secret_access_key e93226059eb069c73f4c2738187b0a881fb403fa

    # Pull data from DVC remote (DagsHub)
    - name: Pull data from DVC remote
      run: |
        dvc pull  # Pull data from the configured remote (DagsHub)    

    - name: Run Data Loader
      run: python src/data_loader.py

    - name: Run Preprocessing
      run: python src/preprocessing.py

    - name: Train Model
      run: python src/train_model.py

    - name: Evaluate Model
      run: python src/evaluate_model.py
