name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace '3.x' with the Python version your app needs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Notify Streamlit Cloud
        run: |
          curl -X POST https://share.streamlit.io/deploy --header 'Content-Type: application/json' --data '{"repository": "allmamun556/MLOPS_CI_CD_MONITORING"}'
